language: c
sudo: false

cache:
  directories:
  - $HOME/.stack

before_install:
  # stack
  - mkdir -p ~/.local/bin
  - mkdir -p ~/tmp
  - export PATH=~/.local/bin:$PATH
  - curl -L https://github.com/commercialhaskell/stack/releases/download/v1.6.5/stack-1.6.5-linux-x86_64.tar.gz | tar xz -C ~/tmp
  - mv ~/tmp/stack-1.6.5-linux-x86_64/stack ~/.local/bin/

matrix:
  include:
    - env: GHCVER=7.10.2 STACK_YAML=stack-7.10.yaml
      addons: {apt: {packages: [ghc-7.10.2],sources: [hvr-ghc]}}
    - env: GHCVER=8.0.2 STACK_YAML=stack-8.0.2.yaml
      addons: {apt: {packages: [ghc-8.0.2],sources: [hvr-ghc]}}
    - env: GHCVER=8.2.1 STACK_YAML=stack-8.2.1.yaml
      addons: {apt: {packages: [ghc-8.2.1],sources: [hvr-ghc]}}
    - env: GHCVER=8.4.2 STACK_YAML=stack-8.4.2.yaml
      addons: {apt: {packages: [ghc-8.4.2],sources: [hvr-ghc]}}
    - env: GHCVER=head STACK_YAML=stack-head.yaml
      addons: {apt: {packages: [cabal-install-head,ghc-head],  sources: [hvr-ghc]}}

  allow_failures:
   - env: GHCVER=head STACK_YAML=stack-head

install:
  - stack --no-terminal --skip-ghc-check setup
  - stack --no-terminal --skip-ghc-check install happy alex

script:
  - make test
